# Generated by Django 4.2.4 on 2023-09-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=24)),
                ("nickname", models.CharField(max_length=255)),
                ("nickname1", models.CharField(default=None, max_length=255)),
                (
                    "nickname2",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "nickname3",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "nickname4",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "nickname5",
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserModel1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=24)),
                ("nickname", models.CharField(max_length=255)),
                ("nickname1", models.CharField(default=None, max_length=255)),
                (
                    "nickname2",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "nickname3",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "nickname4",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "nickname5",
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
        ),
    ]
